### ISSUE TITLE
When doing Killall @e kill the mobs again and again

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#20] opened 2020-06-25 20:56 UTC
**Describe the bug**
A clear and concise description of what the bug is:

When doing killall @e and respawn the mobs dies over again and again when you die or you relog onto the server. 

**To Reproduce**
1. do ./kill @e and it will show you 

**Expected behavior**
A clear and concise description of what you expected to happen:

For it not to show mobs to get killed over and over again. When relog or when doing ./kill

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/104596540bbfbce169aff545f37c9846

https://gyazo.com/917c54605f995efab40acd287a2a6efc

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here: no error

**Comment by kwright02** [comment] 2020-10-12 01:48
Fixed in latest release.

**Closed by kwright02** 2020-10-12 01:48 UTC
Labels: bug

**Comment by jahangir6969** [comment] 2020-10-12 20:05
Can this be reopen. As this issue is not fixed.

**Comment by jahangir6969** [comment] 2020-10-12 20:07
https://youtu.be/6vspaCLqFeY

**Comment by kwright02** [comment] 2020-10-12 20:59
It's not replicable by me. What mods are you using?

**Comment by kwright02** [comment] 2020-10-12 21:03
Never mind, what you're reporting isn't a bug. It's just a by product of the way rendering works

**Comment by jahangir6969** [comment] 2020-10-12 21:22
I check on an paper server and normal mc server. I do not get this render issue plus other clients get the same issue.

**Comment by SizzlinSeal** [comment] 2020-10-12 23:22
does it do the same with essentials?

**Comment by kwright02** [comment] 2020-10-13 04:08
It's just a visual thing. The game isn't affected at all. Ignore it

**Comment by HackuJacku** [comment] 2020-10-13 09:27
This has been happening for me too. When testing it on a Paper 1.15 server (not using Magma), it does not occur. When testing on a 1.15 server (using Magma), it occurs.

**Comment by kwright02** [comment] 2020-10-13 16:59
Again, ignore it, it's irrelevant

**Comment by jahangir6969** [comment] 2020-10-13 18:49
Sorry but it not acceptable at all. As I have replicate this issue in now in windows 10, server 2016 and Linux. So not sure how you cannot replicate it and if someone run this command. it basically would mess something server up and cause lag issue as this happens if someone log off and log back on or leave the chunk and arrive back. Ik you cannot give access to user or an player but it not an fixed. It fairs it not going to be an common issue but still is an issue if someone does it and they no fixes or even and work around for it. As it cause lag and if someone has an junk machine is cause the client/drops they frames ever badly.

**Comment by kwright02** [comment] 2020-10-13 20:11
I'm unable to replicate it after a total of 30 attempts now. There is no lag caused by running that command, and nothing breaks. I'm sorry you're experiencing this issue but there's nothing I can do if I can't replicate it.
